"""Guard against publishing real data or real results.

The project is intended to be shareable, including via a public repository. The
failure mode that guard protects against is not subtle but it is permanent: a
real dissolution database committed once is forked, cached and indexed, and
removing it in a later commit does not remove it from history.

So the rule is enforced rather than documented: data files are ignored by
default, and only the explicitly-labelled synthetic placeholder is allowed.

Skipped when the project is not a git checkout — these tests describe git
behaviour and have nothing to assert without it.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
GIT = shutil.which("git")

#: Anything matching these is a database. Only a placeholder may be published.
DATA_SUFFIXES = {".xlsx", ".xls", ".xlsm", ".csv", ".tsv", ".parquet"}

#: The marker that identifies a database as non-experimental development data.
PLACEHOLDER_MARKER = "PLACEHOLDER"


def _is_git_repo() -> bool:
    if GIT is None:
        return False
    result = subprocess.run(
        [GIT, "rev-parse", "--is-inside-work-tree"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0 and result.stdout.strip() == "true"


def _tracked_files() -> list[str]:
    assert GIT is not None
    result = subprocess.run(
        [GIT, "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True
    )
    return [line for line in result.stdout.splitlines() if line.strip()]


requires_git = pytest.mark.skipif(
    not _is_git_repo(), reason="not a git checkout; nothing to assert about tracking"
)


@requires_git
def test_no_real_database_is_tracked() -> None:
    """Only a database labelled PLACEHOLDER may be committed."""
    offenders = [
        name
        for name in _tracked_files()
        if Path(name).suffix.lower() in DATA_SUFFIXES
        and PLACEHOLDER_MARKER not in Path(name).name.upper()
    ]
    assert not offenders, (
        "A database that is not marked PLACEHOLDER is tracked by git: "
        f"{offenders}. If this is real formulation data, do NOT push it — a public "
        "repository cannot be un-published, and removing the file in a later commit "
        "leaves it in history. Untrack it with `git rm --cached <file>`."
    )


@requires_git
def test_generated_outputs_are_not_tracked() -> None:
    """Derived artifacts leak results as surely as the data leaks inputs."""
    generated_prefixes = ("outputs/", "dist/")
    generated_files = {"dashboard/data.js", "docs/guidelines.md"}
    offenders = [
        name
        for name in _tracked_files()
        if name.startswith(generated_prefixes) or name in generated_files
    ]
    assert not offenders, (
        f"Generated artifacts are tracked: {offenders}. These are regenerated by "
        "`python -m pipeline.run` and, on a real database, would publish the analysis "
        "results. Untrack with `git rm -r --cached <path>`."
    )


@requires_git
def test_no_local_environment_files_are_tracked() -> None:
    offenders = [
        name
        for name in _tracked_files()
        if name.startswith(("node_modules/", ".venv/", "venv/"))
        or name.endswith((".pyc", ".pyo"))
        or name in {"package.json", "package-lock.json"}
    ]
    assert not offenders, f"machine-specific files are tracked: {offenders}"


def test_gitignore_ignores_databases_by_default() -> None:
    """The rule must be a default-deny, not a list of known filenames."""
    text = (ROOT / ".gitignore").read_text(encoding="utf-8")
    assert "*.xlsx" in text, "databases are not ignored by default"
    assert "!CR_matrix_tablet_dissolution_PLACEHOLDER" in text, (
        "the synthetic placeholder should be re-allowed explicitly, so that running "
        "the pipeline works straight from a fresh clone"
    )


@requires_git
def test_placeholder_database_is_still_publishable() -> None:
    """A fresh clone must be able to run the pipeline without extra downloads."""
    assert GIT is not None
    candidates = sorted(ROOT.glob("*PLACEHOLDER*.xlsx"))
    if not candidates:
        pytest.skip("no placeholder database present")
    result = subprocess.run(
        [GIT, "check-ignore", "-q", candidates[0].name],
        cwd=ROOT,
        capture_output=True,
        check=False,
    )
    # check-ignore exits 0 when the path IS ignored.
    assert result.returncode != 0, (
        f"{candidates[0].name} is ignored, so a fresh clone would have no database to "
        "run against. The negation rule in .gitignore is not matching it."
    )
